### ISSUE TITLE
No "get.ledger.voter.jsonld" file in bedrock-docs node module

### ISSUE THREAD

**Issue by cedricf** [veres-one/veres-one#12]
When running a new VeresOne network by following the instructions in the Veres One Developer Quickstart the system fails with:

2018-03-14T08:48:57.235Z - error: [bedrock-docs] Failed to locate REST API documentation file. workerPid=12092, details={
  "name": "NotFoundError",
  "message": "Failed to locate REST API documentation file.",
  "details": {
    "docFiles": [
      "/veres-one/node_modules/bedrock-docs/docs/examples/get.ledger.voter.jsonld"
    ],
    "section": "examples/get.ledger.voter.jsonld"
  },
  "cause": null
}

The **get.ledger.voter.jsonld** does not exist in the bedrock-docs node module.

**Comment by mattcollier** [comment]
Hello, that error may be safely ignored as it indicates that a REST/Express endpoint has not been properly documented.  

That error should not be preventing your node from operating.  What are your other symptoms/errors?

**Comment by cedricf** [comment]
My node is crashing. See the log below.  I thought it might be related.

2018-03-15T06:59:02.986Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /ledger-agents workerPid=12512
2018-03-15T06:59:02.986Z - error: [bedrock-docs] Failed to locate REST API documentation file. workerPid=12512, details={
  "name": "NotFoundError",
  "message": "Failed to locate REST API documentation file.",
  "details": {
    "docFiles": [
      "/veres-one/node_modules/bedrock-docs/docs/examples/get.ledger.jsonld"
    ],
    "section": "examples/get.ledger.jsonld"
  },
  "cause": null
}
2018-03-15T06:59:02.987Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /ledger-agents/{agentId} workerPid=12512
2018-03-15T06:59:02.987Z - error: [bedrock-docs] Failed to locate REST API documentation file. workerPid=12512, details={
  "name": "NotFoundError",
  "message": "Failed to locate REST API documentation file.",
  "details": {
    "docFiles": [
      "/veres-one/node_modules/bedrock-docs/docs/examples/get.ledger.event.jsonld"
    ],
    "section": "examples/get.ledger.event.jsonld"
  },
  "cause": null
}
2018-03-15T06:59:02.988Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /ledger-agents/{agentId}/blocks workerPid=12512
2018-03-15T06:59:02.988Z - error: [bedrock-docs] Failed to locate REST API documentation file. workerPid=12512, details={
  "name": "NotFoundError",
  "message": "Failed to locate REST API documentation file.",
  "details": {
    "docFiles": [
      "/veres-one/node_modules/bedrock-docs/docs/examples/get.ledger.event.jsonld"
    ],
    "section": "examples/get.ledger.event.jsonld"
  },
  "cause": null
}
2018-03-15T06:59:02.989Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /ledger-agents/{agentId}/events workerPid=12512
2018-03-15T06:59:02.989Z - warning: [bedrock-docs] no HTTP API documentation exists for POST /ledger-agents/{agentId}/query workerPid=12512
2018-03-15T06:59:02.990Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /modules* workerPid=12512
2018-03-15T06:59:02.990Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /session workerPid=12512
2018-03-15T06:59:02.991Z - warning: [bedrock-docs] no HTTP API documentation exists for GET /session/logout workerPid=12512
2018-03-15T06:59:02.991Z - debug: [bedrock-docs] RAML file stored successfully workerPid=12512, details={
  "fileName": "/tmp/genesis.veres.one.localhost-pid-12512.raml"
}
2018-03-15T06:59:03.619Z - debug: [bedrock-docs] RAML rendered to HTML successfully workerPid=12512
2018-03-15T06:59:04.485Z - critical: worker: uncaught error: TypeError: Cannot read property 'id' of undefined
    at async.auto.create (/veres-one/lib/ledger.js:184:45)
    at runTask (/veres-one/node_modules/async/dist/async.js:1618:13)
    at /veres-one/node_modules/async/dist/async.js:1558:13
    at processQueue (/veres-one/node_modules/async/dist/async.js:1568:13)
    at taskComplete (/veres-one/node_modules/async/dist/async.js:1587:9)
    at /veres-one/node_modules/async/dist/async.js:1611:17
    at /veres-one/node_modules/async/dist/async.js:958:16
    at async.auto (/veres-one/lib/ledger.js:175:9)
    at /veres-one/node_modules/async/dist/async.js:473:16
    at processQueue (/veres-one/node_modules/async/dist/async.js:1564:20)
    at taskComplete (/veres-one/node_modules/async/dist/async.js:1587:9)
    at /veres-one/node_modules/async/dist/async.js:1611:17
    at /veres-one/node_modules/async/dist/async.js:958:16
    at api.nextTick (/veres-one/node_modules/jsonld-signatures/lib/util.js:138:22)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) workerPid=12512
2018-03-15T06:59:04.512Z - critical: worker 12512 exited with code 1

**Comment by mattcollier** [comment]
Sorry you're having difficulties.  Let's make sure we get the basics covered.  Please let us know your OS, node version, mongo version and redis version.  The requirements are:
- node 8.6+
- MongoDB 3.6+
- Redis 4.0
- also need to make sure you have a functioning c/c++ toolchain for compiling native binaries.  When you did 'npm install' did you see any errors?

**Comment by cedricf** [comment]
Node v8.10.0
MongoDB v3.6.3
Redis 4.0.8

Here is the npm install output.  There are a lot of warnings.
npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> equihash@0.0.1-0 install /veres-one/node_modules/equihash-signature/node_modules/equihash
> node-gyp rebuild

make: Entering directory '/veres-one/node_modules/equihash-signature/node_modules/equihash/build'
  CXX(target) Release/obj.target/khovratovich/lib/khovratovich/addon.o
../lib/khovratovich/addon.cc: In member function 'virtual void EquihashSolveWorker::HandleOKCallback()':
../lib/khovratovich/addon.cc:87:31: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
         callback->Call(2, argv);
                               ^
In file included from ../lib/khovratovich/addon.cc:12:0:
../../../../nan/nan.h:1568:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../lib/khovratovich/addon.cc: In member function 'virtual void EquihashVerifyWorker::HandleOKCallback()':
../lib/khovratovich/addon.cc:120:31: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
         callback->Call(2, argv);
                               ^
In file included from ../lib/khovratovich/addon.cc:12:0:
../../../../nan/nan.h:1568:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/khovratovich/lib/khovratovich/pow.o
  CXX(target) Release/obj.target/khovratovich/lib/khovratovich/blake/blake2b.o
  SOLINK_MODULE(target) Release/obj.target/khovratovich.node
  COPY Release/khovratovich.node
make: Leaving directory '/veres-one/node_modules/equihash-signature/node_modules/equihash/build'
npm WARN lifecycle veres-one@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) veres-one@0.0.1 node genesis.veres.one.localhost.js compile-less /veres-one
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-agreement@1.0.2 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-agreement@1.0.2 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-authn-did@3.1.1 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-authn-did-jwt@1.1.0 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-authn-password@3.0.5 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-authn-password@3.0.5 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-consumer@2.0.6 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-credentials-mongodb@3.3.1 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-credentials-mongodb@3.3.1 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-credentials-rest@1.2.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-credentials-rest@1.2.0 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-did-client@1.1.2-0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-docs@2.2.2 requires a peer of bedrock@^1.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-event-log@2.1.2 requires a peer of bedrock@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-event-log@2.1.2 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-express@2.0.8 requires a peer of bedrock@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-i18n@2.0.1 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-identity@4.6.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-identity@4.6.0 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-identity-http@1.2.1 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-identity-http@1.2.1 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-issuer@1.2.2 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-issuer@1.2.2 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-jobs@2.0.3 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-jobs@2.0.3 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-key@4.1.0 requires a peer of bedrock@^1.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-key-http@2.2.0 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-key-http@2.2.0 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-agent@0.1.0-0 requires a peer of bedrock@^1.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-consensus-continuity@0.0.1-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-consensus-continuity@0.0.1-0 requires a peer of bedrock-did-client@^1.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-context@0.3.6-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-node@0.3.6-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-storage-mongodb@0.2.1-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-validator-equihash@0.0.1-0 requires a peer of bedrock@^1.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-validator-equihash@0.0.1-0 requires a peer of bedrock-ledger-node@^0.3.5 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-ledger-validator-signature@0.0.1-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-mail@2.0.4 requires a peer of bedrock@^1.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-mongodb@5.1.2 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-passport@3.4.2 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-passport@3.4.2 requires a peer of bedrock-did-client@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-permission@2.4.3 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-permission@2.4.3 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-protractor@3.3.1-0 requires a peer of bedrock@^1.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-redis@3.2.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-request-limiter@2.0.1 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-rest@2.1.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-server@2.3.1 requires a peer of bedrock@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-session-http@3.0.2 requires a peer of bedrock@^1.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-session-mongodb@2.0.3 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-session-mongodb@2.0.3 requires a peer of bedrock-mongodb@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-test@2.0.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-validation@2.3.0 requires a peer of bedrock@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-views@5.3.0 requires a peer of bedrock@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-webpack@1.2.0 requires a peer of bedrock@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-website-user-http@1.0.2 requires a peer of bedrock@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-website-user-http@1.0.2 requires a peer of bedrock-key@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bedrock-website-user-http@1.0.2 requires a peer of bedrock-mongodb@^3.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-shell@2.1.0 requires a peer of grunt@>=0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN veres-one-context@0.1.0-0 requires a peer of bedrock@digitalbazaar/bedrock#jsonld-1.1 but none is installed. You must install peer dependencies yourself.
npm WARN veres-one-context@0.1.0-0 requires a peer of bedrock-ledger-context@digitalbazaar/bedrock-ledger-context but none is installed. You must install peer dependencies yourself.
npm WARN veres-one-validator@0.1.0-0 requires a peer of bedrock@^1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN veres-one-validator@0.1.0-0 requires a peer of veres-one-context@digitalbazaar/veres-one-context but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2 packages, removed 1 package, updated 3 packages and moved 1 package in 31.272s

**Comment by mattcollier** [comment]
@cedricf I gather from your report that you are running OSX.  We have not done any testing on OSX yet, but we are going to look into that.  I'll report back soon.

**Comment by cedricf** [comment]
I am actually trying to set it up in an Ubuntu docker image on my mac.

**Comment by msporny** [comment]
> I am actually trying to set it up in an Ubuntu docker image on my mac.

This sounds like a half-initialized dev database problem. Try dropping your veres_one_localhost_genesis MongoDB database and reset your Redis database and try again.

The failure is happening on this line:

https://github.com/veres-one/veres-one/blob/master/lib/ledger.js#L184

Which means that the call to get the database owner for the veres one genesis database failed for some reason:

https://github.com/veres-one/veres-one/blob/master/lib/ledger.js#L261

That typically happens when the genesis node was brought up previously in a funky state. If you want a quick shell script to wipe the development databases, use this:

```
#!/usr/bin/env sh
#
# Drop the Veres One dev and test databases for genesis and peer nodes

mongo --eval "db = db.getSiblingDB('veres_one_localhost_genesis'); db.dropDatabase()"
mongo --eval "db = db.getSiblingDB('veres_one_test'); db.dropDatabase()"

for PEER in `seq 1 3`;
do
  mongo --eval "db = db.getSiblingDB('veres_one_localhost_peer_$PEER'); db.dropDatabase()"
done
```

We use the script above when new dev code lands so we can make sure we're starting w/ a clean database in dev mode.

**Comment by davidlehn** [comment]
In case it helps, server starts up on macos sierra with mongodb, redis-server, and node@8 installed from brew.

A while ago I started the configs to make everything run via docker compose.  They are out of date now.  I'll try to find time to fix and polish those.

**Comment by cedricf** [comment]
OK. Thanks for the feedback.

**Comment by Josh-Payne** [comment]
I'm having this problem as well (OSX). @davidlehn where can I find those configs?
