### ISSUE TITLE
can't npm install on Osx

### ISSUE THREAD

**Issue by bakatest-me** [veres-one/veres-one#24]
![screen shot 2561-11-23 at 00 08 08](https://user-images.githubusercontent.com/22494087/48916208-fb736300-eeb3-11e8-9b96-b25bf9b43cc4.png)
![screen shot 2561-11-23 at 00 08 34](https://user-images.githubusercontent.com/22494087/48916211-fc0bf980-eeb3-11e8-9f9b-f9d0bbe9478c.png)

**Comment by msporny** [comment]
Thanks for the issue report, @bakatest-me -- looks like some branches have disappeared? Pulling in some of our engineers to dig deeper into this issue.

**Comment by dmitrizagidulin** [comment]
@bakatest-me Thanks for the heads up. As we're racing towards another Testnet release, the libraries are currently in transition. The short version is - `master` is currently not installable, please try and use `elector-pool-support` branch instead.

(We should probably make a note on the master README, to this end)

**Comment by dmitrizagidulin** [comment]
@bakatest-me Just as a heads up, the elector pool branch has been merged into `update-releases-deps`, so now that's the one to use!

**Comment by creatornader** [comment]
Hey, following up on this issue. Is `master` still uninstallable? I got a similar error doing `npm install` on Ubuntu 16.04.

`npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
loadDep:veres-one-validat ▐ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git rev-list -n1 cliParsed: fatal: ambiguous argument 'cliParsed': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 cliParsed: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 cliParsed: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 cliParsed: 
npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
loadDep:veres-one-validat ▄ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git rev-list -n1 cliParsed: fatal: ambiguous argument 'cliParsed': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 cliParsed: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 cliParsed: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 cliParsed: 
loadDep:veres-one-validat ▌ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine bedrock-ledger-storage-mongodb@2.3.1-0: wanted: {"node":">=6.3.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine bedrock-ledger-node@8.0.2-0: wanted: {"node":">=8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:veres-one-validat ▐ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
npm ERR! git rev-list -n1 jsonld-1.1: fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 jsonld-1.1: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 jsonld-1.1: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 jsonld-1.1: 
npm ERR! git rev-list -n1 cliParsed: fatal: ambiguous argument 'cliParsed': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 cliParsed: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 cliParsed: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 cliParsed: 
npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 jsonld-1.1
npm ERR! fatal: ambiguous argument 'jsonld-1.1': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
`

**Comment by mattcollier** [comment]
@creatornader Thanks for the report.  We are still working towards a testnet v2 release.  This branch should install and and for you: https://github.com/veres-one/veres-one/tree/testnet_v2

**Comment by creatornader** [comment]
@mattcollier Thanks for the quick reply. It looked like it wasn't going to fail, but at the very end it threw this message for me. For the record, my node version is  v4.2.6 and my npm version is v3.5.2.

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
npm WARN bedrock-identity-http@2.0.0 requires a peer of bedrock-docs@^2.0.0 but none was installed.
npm WARN bedrock-identity-http@2.0.0 requires a peer of bedrock-validation@^3.1.0 but none was installed.
npm WARN bedrock-identity@4.6.0 requires a peer of bedrock-mongodb@^3.0.0 but none was installed.
npm WARN bedrock-rest@2.1.3 requires a peer of bedrock-views@^5.0.0 but none was installed.
npm WARN bedrock-passport@3.4.2 requires a peer of bedrock-did-client@^1.0.0 but none was installed.
npm WARN bedrock-ledger-consensus-continuity-es-most-recent-participants@2.1.0 requires a peer of bedrock-ledger-node@^7.0.0 but none was installed.
npm WARN bedrock-veres-one-context@6.0.0 requires a peer of bedrock-ledger-context@^10.0.0 but none was installed.
npm WARN veres-one-consensus-continuity-elector-selection@0.0.1-0 requires a peer of bedrock-ledger-node@^3.0.0 but none was installed.
npm WARN veres-one-consensus-continuity-elector-selection@0.0.1-0 requires a peer of bedrock-veres-one-context@^5.0.0 but none was installed.
npm WARN veres-one-validator@5.0.1-0 requires a peer of bedrock-ledger-utils@^1.0.0 but none was installed.
npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

> npm ERR! sodium-native@2.3.0 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.3.0 install script 'node-gyp-build "node preinstall.js" "node postinstall.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build "node preinstall.js" "node postinstall.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium-native
npm ERR! There is likely additional logging output above.

**Comment by mattcollier** [comment]
@creatornader looks like there's a problem building the `sodium-native` (native crypto library)

You'll need to ensure that you have you have a C/C++ toolchain to build the sodium-native code.  There's some guidance here: https://github.com/nodejs/node-gyp

**Comment by creatornader** [comment]
@mattcollier Gotcha. Was able to fix it by running ` apt-get install autoconf automake g++ libtool`. I already had python, gcc, g++, and make (`build-essential` for ubuntu) so I had to do some digging to find it. Thanks for the help. Getting an `UNMET PEER DEPENDENCY ERROR` now but its progress!

> ..   
  CXX(target) Release/obj.target/sodium/src/crypto_pwhash_str_async.o
  CXX(target) Release/obj.target/sodium/src/crypto_pwhash_str_verify_async.o
  SOLINK_MODULE(target) Release/obj.target/sodium.node
  COPY Release/sodium.node
make: Leaving directory '/home/nader/Danube/veres-one/node_modules/sodium-native/build'
veres-one@0.0.1 /home/nader/Danube/veres-one
├── UNMET PEER DEPENDENCY bedrock-did-client@2.0.0 (git://github.com/digitalbazaar/bedrock-did-client.git#8cc68895fc178a4e230a83ec0753991b27a6a494)
├── UNMET PEER DEPENDENCY bedrock-docs@3.1.0
├─┬ bedrock-ledger-consensus-continuity@3.3.0
│ └── crypto-ld@3.5.2 
├── UNMET PEER DEPENDENCY bedrock-ledger-context@11.0.0
├── UNMET PEER DEPENDENCY bedrock-ledger-node@8.0.1
├── UNMET PEER DEPENDENCY bedrock-ledger-utils@0.0.1-0 (git://github.com/digitalbazaar/bedrock-ledger-utils.git#9a83d5bd71736a7f54fee9ebe20ca97c1ed52052)
├─┬ UNMET PEER DEPENDENCY bedrock-mongodb@5.5.0
│ └─┬ sodium-native@2.3.0 
│   └── node-gyp-build@3.8.0 
├── UNMET PEER DEPENDENCY bedrock-validation@4.1.0
├── UNMET PEER DEPENDENCY bedrock-veres-one-context@6.0.0
└── UNMET PEER DEPENDENCY bedrock-views@6.5.0

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.8
npm WARN bedrock-identity@4.6.0 requires a peer of bedrock-mongodb@^3.0.0 but none was installed.
npm WARN bedrock-identity-http@2.0.0 requires a peer of bedrock-docs@^2.0.0 but none was installed.
npm WARN bedrock-identity-http@2.0.0 requires a peer of bedrock-validation@^3.1.0 but none was installed.
npm WARN bedrock-ledger-consensus-continuity-es-most-recent-participants@2.1.0 requires a peer of bedrock-ledger-node@^7.0.0 but none was installed.
npm WARN bedrock-passport@3.4.2 requires a peer of bedrock-did-client@^1.0.0 but none was installed.
npm WARN bedrock-rest@2.1.3 requires a peer of bedrock-views@^5.0.0 but none was installed.
npm WARN bedrock-veres-one-context@6.0.0 requires a peer of bedrock-ledger-context@^10.0.0 but none was installed.
npm WARN veres-one-consensus-continuity-elector-selection@0.0.1-0 requires a peer of bedrock-ledger-node@^3.0.0 but none was installed.
npm WARN veres-one-consensus-continuity-elector-selection@0.0.1-0 requires a peer of bedrock-veres-one-context@^5.0.0 but none was installed.
npm WARN veres-one-validator@5.0.1-0 requires a peer of bedrock-ledger-utils@^1.0.0 but none was installed.

**Comment by mattcollier** [comment]
You *should* be able to safely ignore all those peer dependency errors which arise out of using dev branches and out of date package files.  Let us know if there is an issue related to this.

**Comment by creatornader** [comment]
Unfortunately when I ignore the npm warnings and try to run `node genesis.veres.one.localhost.js` I immediately get this short error message. Also, I can move this to a separate (new) issue so as to not clog this thread.

> /home/nader/Danube/veres-one/node_modules/bedrock/lib/util.js:117
let {cause} = err;
          ^

> SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/nader/Danube/veres-one/node_modules/bedrock/lib/bedrock.js:7:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by mattcollier** [comment]
> For the record, my node version is v4.2.6 and my npm version is v3.5.2.

Unfortunately, this code is not compatible with Node 4.x was EOL's in April of 2018.  We require node 10.x, the current LTS release.  I'll make an issue to ensure that the system requirements are properly outlined in the readme.

**Comment by creatornader** [comment]
Ah, understood. Will try to whip up a Docker image for this. Thanks again.
