### ISSUE TITLE
Ledger agent not found

### ISSUE THREAD

**Issue by aljones15** [veres-one/veres-one#41]
Branch: master

Steps:
1. Delete node_modules
2. `npm i`
3. `npm start`

Error:

```js
Could not fetch ledger agent. WebLedgerClientError [NotFoundError]: Ledger agent not found.
    at WebLedgerClient.getAgent (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:343:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebLedgerClient.getServiceEndpoint (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:174:7)
    at async WebLedgerClient.getDocument (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:127:21)
    at async WebLedgerClient.getGenesisBlock (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:159:32)
    at async RetryOperation._fn (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/p-retry/index.js:41:12) {
  details: { id: undefined }
}
2020-10-08T13:37:15.380Z - error: [veres-one] Unable to acquire the genesis block. Retrying... error=NotFoundError: Ledger agent not found.
    at WebLedgerClient.getAgent (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:343:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebLedgerClient.getServiceEndpoint (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:174:7)
    at async WebLedgerClient.getDocument (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:127:21)
    at async WebLedgerClient.getGenesisBlock (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/web-ledger-client/lib/WebLedgerClient.js:159:32)
    at async RetryOperation._fn (/home/liminal18/Programs/nodeJS/digital_bazaar/veres-one/node_modules/p-retry/index.js:41:12), workerPid=13007, details={
  "error": {
    "name": "NotFoundError",
    "details": {},
    "attemptNumber": 5,
    "retriesLeft": 296
  }
}
```

my `.env` file:
```
BEDROCK_HTTPS_PORT=45443
BEDROCK_HTTP_PORT=45080
BEDROCK_SERVER_HOST=localhost:45443
EXPRESS_SECRET=NOTASECRET
MONGODB_HOST=localhost
MONGODB_NAME=veres_one_node
MONGODB_PORT=27017
NODE_ENV=development
NODE_HOST=localhost
VERES_ONE_GENESIS_NODE=localhost:45443
VERES_ONE_ELECTOR_HOSTS=localhost:45443
```

**Comment by aljones15** [comment]
This was fixedby removing `VERES_ONE_GENESIS_NODE` from the `.env` file.

**Comment by gannan08** [comment]
When starting the genesis node, one should not specify the `VERES_ONE_GENESIS_NODE` variable. The variable is reserved for peer nodes that need to know the location of the genesis node.

Please try again with its removal in the `.env` file.
