### ISSUE TITLE
node-fetch cannot load [object Request]. URL scheme \"did\" is not supported.

### ISSUE THREAD

**Issue by aljones15** [veres-one/veres-one#55]
```js
2021-08-27T21:00:29.506Z - debug: [ledger-consensus-continuity] A non-critical error occurred during gossip workerPid=208926, workerId=4531ef7abb40685f, details={
  "peer": "did:key:z6Mko9r7MyvSa5n8YRiRmKgekdu46haYjeD9acasSE2Wtzhu",
  "error": {
    "message": "Could not get peer history.",
    "stack": "NetworkError: Could not get peer history.\n    at Object.exports.getHistory (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/client.js:109:11)\n    at async _getNeeded (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/gossip.js:210:20)\n    at async _gw (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/gossip.js:109:14)\n    at async exports.runGossipCycle (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/gossip.js:60:9)\n    at async Worker.runGossipCycle (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/Worker.js:201:41)\n    at async _runPipeline (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/pipeline.js:108:43)\n    at async Object.api.run (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-consensus-continuity/lib/worker/pipeline.js:31:5)\n    at async LedgerNodeWorkSession._runAndRelease (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-node/lib/LedgerNodeWorkSession.js:87:7)\n    at async _offer (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-node/lib/consensus.js:197:5)\n    at async Object.api._scheduleConsensusWork (/home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-node/lib/consensus.js:87:24)\n    at async /home/liminal18/Programs/nodejs/veres_one/node-2/node_modules/bedrock-ledger-node/lib/consensus.js:30:9",
    "name": "NetworkError",
    "details": {
      "localPeerId": "did:key:z6MkuNgnfdv4vD1iUiLRjTTyyB25ByZb7sTG3TJL3GiBErTc",
      "remotePeerId": "did:key:z6Mko9r7MyvSa5n8YRiRmKgekdu46haYjeD9acasSE2Wtzhu",
      "url": "did:key:z6Mko9r7MyvSa5n8YRiRmKgekdu46haYjeD9acasSE2Wtzhu/gossip"
    },
    "cause": {
      "name": "NetworkError",
      "message": "node-fetch cannot load [object Request]. URL scheme \"did\" is not supported.",
      "details": {},
      "cause": null
    }
  }
}
```

occurs in `dingo-rc1`. Might be related to using `dids` in the witnessPoolDoc.

**Comment by aljones15** [comment]
This should have been addressed by updating the method we add peer nods here: https://github.com/veres-one/veres-one/pull/51/commits/9351c4360cb9f1fc5e1b2dad5b469fce77df8c62
